### ISSUE TITLE
Rename RsdxPackedCacheFile.bin while mods are enabled

### ISSUE THREAD

**Issue by RagdollClash** [HyperPolygon64/Unleashed-Mod-Manager#1]
Looking into `RsdxPackedCacheFile.bin`, it looks like it's just a cache for arl files in the game. This will cause conflicts to occur with any new file additions within an ar file.

**Comment by hyperbx** [comment]
I just assumed this was another random SELF slipped into the game's data, so I never really looked into it.

Sonic '06 has something similar, for some reason.

I'll deal with this in a moment, cheers for reporting.

**Comment by hyperbx** [comment]
Fixed from commit https://github.com/HyperPolygon64/Unleashed-Mod-Manager/commit/6df935bd359b024a5b3748ec457116395221d5a3. This change will be added to Version 1.02.
