### ISSUE TITLE
Add AR merging

### ISSUE THREAD

**Issue by RagdollClash** [HyperPolygon64/Unleashed-Mod-Manager#4]
Some mods (ex. No HUD) will modify a file in an archive that is commonly modified (ex. character mods). An option to merge the mods together (like ARC merging in Sonic 06 Mod Manager) would help out with a scenario like this.

**Comment by hyperbx** [comment]
I was just thinking about this right now, actually - only problem is decompression, since XCompression and SEGS are still quite unknown, for some reason. Only stuff out there is for QuickBMS, which is bleh.

**Comment by hyperbx** [comment]
Added from commit https://github.com/HyperPolygon64/Unleashed-Mod-Manager/commit/477b225f4f8b3e535d3c42d27f63a112c8c18620. This change has been released with Version 1.04.
